/*
 * generated by Xtext 2.26.0
 */
package iae.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import iae.TemporRuntimeModule;
import iae.TemporStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TemporIdeSetup extends TemporStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TemporRuntimeModule(), new TemporIdeModule()));
	}
	
}
