/**
 * generated by Xtext 2.26.0
 */
package iae.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.tempor.Expr#getObj <em>Obj</em>}</li>
 *   <li>{@link iae.tempor.Expr#getProp <em>Prop</em>}</li>
 * </ul>
 *
 * @see iae.tempor.TemporPackage#getExpr()
 * @model
 * @generated
 */
public interface Expr extends EObject
{
  /**
   * Returns the value of the '<em><b>Obj</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj</em>' attribute.
   * @see #setObj(String)
   * @see iae.tempor.TemporPackage#getExpr_Obj()
   * @model
   * @generated
   */
  String getObj();

  /**
   * Sets the value of the '{@link iae.tempor.Expr#getObj <em>Obj</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj</em>' attribute.
   * @see #getObj()
   * @generated
   */
  void setObj(String value);

  /**
   * Returns the value of the '<em><b>Prop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' attribute.
   * @see #setProp(String)
   * @see iae.tempor.TemporPackage#getExpr_Prop()
   * @model
   * @generated
   */
  String getProp();

  /**
   * Sets the value of the '{@link iae.tempor.Expr#getProp <em>Prop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prop</em>' attribute.
   * @see #getProp()
   * @generated
   */
  void setProp(String value);

} // Expr
