/**
 * generated by Xtext 2.26.0
 */
package iae.tempor;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.tempor.Model#getReq <em>Req</em>}</li>
 * </ul>
 *
 * @see iae.tempor.TemporPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Req</b></em>' containment reference list.
   * The list contents are of type {@link iae.tempor.Requirement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Req</em>' containment reference list.
   * @see iae.tempor.TemporPackage#getModel_Req()
   * @model containment="true"
   * @generated
   */
  EList<Requirement> getReq();

} // Model
