/**
 * generated by Xtext 2.26.0
 */
package iae.tempor;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Requirement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link iae.tempor.Requirement#getTrig <em>Trig</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getInv <em>Inv</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getRea <em>Rea</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getRel <em>Rel</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getInv2 <em>Inv2</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getNotdel <em>Notdel</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getFin <em>Fin</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getNotfin <em>Notfin</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getFin2 <em>Fin2</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getInv3 <em>Inv3</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getRel2 <em>Rel2</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getE1 <em>E1</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getE2 <em>E2</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getE3 <em>E3</em>}</li>
 *   <li>{@link iae.tempor.Requirement#getRea2 <em>Rea2</em>}</li>
 * </ul>
 *
 * @see iae.tempor.TemporPackage#getRequirement()
 * @model
 * @generated
 */
public interface Requirement extends EObject
{
  /**
   * Returns the value of the '<em><b>Trig</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trig</em>' containment reference.
   * @see #setTrig(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Trig()
   * @model containment="true"
   * @generated
   */
  Expr getTrig();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getTrig <em>Trig</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trig</em>' containment reference.
   * @see #getTrig()
   * @generated
   */
  void setTrig(Expr value);

  /**
   * Returns the value of the '<em><b>Inv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inv</em>' containment reference.
   * @see #setInv(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Inv()
   * @model containment="true"
   * @generated
   */
  Expr getInv();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getInv <em>Inv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inv</em>' containment reference.
   * @see #getInv()
   * @generated
   */
  void setInv(Expr value);

  /**
   * Returns the value of the '<em><b>Rea</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rea</em>' containment reference.
   * @see #setRea(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Rea()
   * @model containment="true"
   * @generated
   */
  Expr getRea();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getRea <em>Rea</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rea</em>' containment reference.
   * @see #getRea()
   * @generated
   */
  void setRea(Expr value);

  /**
   * Returns the value of the '<em><b>Rel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel</em>' containment reference.
   * @see #setRel(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Rel()
   * @model containment="true"
   * @generated
   */
  Expr getRel();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getRel <em>Rel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel</em>' containment reference.
   * @see #getRel()
   * @generated
   */
  void setRel(Expr value);

  /**
   * Returns the value of the '<em><b>Inv2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inv2</em>' containment reference.
   * @see #setInv2(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Inv2()
   * @model containment="true"
   * @generated
   */
  Expr getInv2();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getInv2 <em>Inv2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inv2</em>' containment reference.
   * @see #getInv2()
   * @generated
   */
  void setInv2(Expr value);

  /**
   * Returns the value of the '<em><b>Notdel</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notdel</em>' containment reference.
   * @see #setNotdel(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Notdel()
   * @model containment="true"
   * @generated
   */
  Expr getNotdel();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getNotdel <em>Notdel</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notdel</em>' containment reference.
   * @see #getNotdel()
   * @generated
   */
  void setNotdel(Expr value);

  /**
   * Returns the value of the '<em><b>Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin</em>' containment reference.
   * @see #setFin(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Fin()
   * @model containment="true"
   * @generated
   */
  Expr getFin();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getFin <em>Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin</em>' containment reference.
   * @see #getFin()
   * @generated
   */
  void setFin(Expr value);

  /**
   * Returns the value of the '<em><b>Notfin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notfin</em>' containment reference.
   * @see #setNotfin(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Notfin()
   * @model containment="true"
   * @generated
   */
  Expr getNotfin();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getNotfin <em>Notfin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notfin</em>' containment reference.
   * @see #getNotfin()
   * @generated
   */
  void setNotfin(Expr value);

  /**
   * Returns the value of the '<em><b>Fin2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin2</em>' containment reference.
   * @see #setFin2(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Fin2()
   * @model containment="true"
   * @generated
   */
  Expr getFin2();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getFin2 <em>Fin2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin2</em>' containment reference.
   * @see #getFin2()
   * @generated
   */
  void setFin2(Expr value);

  /**
   * Returns the value of the '<em><b>Inv3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inv3</em>' containment reference.
   * @see #setInv3(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Inv3()
   * @model containment="true"
   * @generated
   */
  Expr getInv3();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getInv3 <em>Inv3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inv3</em>' containment reference.
   * @see #getInv3()
   * @generated
   */
  void setInv3(Expr value);

  /**
   * Returns the value of the '<em><b>Rel2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rel2</em>' containment reference.
   * @see #setRel2(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Rel2()
   * @model containment="true"
   * @generated
   */
  Expr getRel2();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getRel2 <em>Rel2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rel2</em>' containment reference.
   * @see #getRel2()
   * @generated
   */
  void setRel2(Expr value);

  /**
   * Returns the value of the '<em><b>E1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E1</em>' containment reference.
   * @see #setE1(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_E1()
   * @model containment="true"
   * @generated
   */
  Expr getE1();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getE1 <em>E1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E1</em>' containment reference.
   * @see #getE1()
   * @generated
   */
  void setE1(Expr value);

  /**
   * Returns the value of the '<em><b>E2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E2</em>' containment reference.
   * @see #setE2(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_E2()
   * @model containment="true"
   * @generated
   */
  Expr getE2();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getE2 <em>E2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E2</em>' containment reference.
   * @see #getE2()
   * @generated
   */
  void setE2(Expr value);

  /**
   * Returns the value of the '<em><b>E3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>E3</em>' containment reference.
   * @see #setE3(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_E3()
   * @model containment="true"
   * @generated
   */
  Expr getE3();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getE3 <em>E3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>E3</em>' containment reference.
   * @see #getE3()
   * @generated
   */
  void setE3(Expr value);

  /**
   * Returns the value of the '<em><b>Rea2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rea2</em>' containment reference.
   * @see #setRea2(Expr)
   * @see iae.tempor.TemporPackage#getRequirement_Rea2()
   * @model containment="true"
   * @generated
   */
  Expr getRea2();

  /**
   * Sets the value of the '{@link iae.tempor.Requirement#getRea2 <em>Rea2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rea2</em>' containment reference.
   * @see #getRea2()
   * @generated
   */
  void setRea2(Expr value);

} // Requirement
