/*
 * generated by Xtext 2.26.0
 */
package iae.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TemporUiModule extends AbstractTemporUiModule {

	public TemporUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
