/*
 * generated by Xtext 2.26.0
 */
package iae.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTemporScopeProvider extends DelegatingScopeProvider {
}
