/*
 * generated by Xtext 2.26.0
 */
package iae.parser.antlr;

import com.google.inject.Inject;
import iae.parser.antlr.internal.InternalTemporParser;
import iae.services.TemporGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TemporParser extends AbstractAntlrParser {

	@Inject
	private TemporGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTemporParser createParser(XtextTokenStream stream) {
		return new InternalTemporParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public TemporGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TemporGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
