/*
 * generated by Xtext 2.26.0
 */
package iae.ui;

import com.google.inject.Injector;
import iae.tempor.ui.internal.TemporActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TemporExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TemporActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TemporActivator activator = TemporActivator.getInstance();
		return activator != null ? activator.getInjector(TemporActivator.IAE_TEMPOR) : null;
	}

}
