/*
 * generated by Xtext 2.26.0
 */
package iae.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import iae.ide.contentassist.antlr.internal.InternalTemporParser;
import iae.services.TemporGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class TemporParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TemporGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TemporGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getRequirementAccess().getAlternatives(), "rule__Requirement__Alternatives");
			builder.put(grammarAccess.getDotAccess().getAlternatives(), "rule__Dot__Alternatives");
			builder.put(grammarAccess.getRequirementAccess().getGroup_0(), "rule__Requirement__Group_0__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_1(), "rule__Requirement__Group_1__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_2(), "rule__Requirement__Group_2__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_3(), "rule__Requirement__Group_3__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_4(), "rule__Requirement__Group_4__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_5(), "rule__Requirement__Group_5__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_6(), "rule__Requirement__Group_6__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_7(), "rule__Requirement__Group_7__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_8(), "rule__Requirement__Group_8__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_9(), "rule__Requirement__Group_9__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_10(), "rule__Requirement__Group_10__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_11(), "rule__Requirement__Group_11__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_12(), "rule__Requirement__Group_12__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_13(), "rule__Requirement__Group_13__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_14(), "rule__Requirement__Group_14__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_15(), "rule__Requirement__Group_15__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_16(), "rule__Requirement__Group_16__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_17(), "rule__Requirement__Group_17__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_18(), "rule__Requirement__Group_18__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_19(), "rule__Requirement__Group_19__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_20(), "rule__Requirement__Group_20__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_21(), "rule__Requirement__Group_21__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_22(), "rule__Requirement__Group_22__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_23(), "rule__Requirement__Group_23__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_24(), "rule__Requirement__Group_24__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_25(), "rule__Requirement__Group_25__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_26(), "rule__Requirement__Group_26__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_27(), "rule__Requirement__Group_27__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_28(), "rule__Requirement__Group_28__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_29(), "rule__Requirement__Group_29__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_30(), "rule__Requirement__Group_30__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_31(), "rule__Requirement__Group_31__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_32(), "rule__Requirement__Group_32__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_33(), "rule__Requirement__Group_33__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_34(), "rule__Requirement__Group_34__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_35(), "rule__Requirement__Group_35__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_36(), "rule__Requirement__Group_36__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_37(), "rule__Requirement__Group_37__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_38(), "rule__Requirement__Group_38__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_39(), "rule__Requirement__Group_39__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_40(), "rule__Requirement__Group_40__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_41(), "rule__Requirement__Group_41__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_42(), "rule__Requirement__Group_42__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_43(), "rule__Requirement__Group_43__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_44(), "rule__Requirement__Group_44__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_45(), "rule__Requirement__Group_45__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_46(), "rule__Requirement__Group_46__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_47(), "rule__Requirement__Group_47__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_48(), "rule__Requirement__Group_48__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_49(), "rule__Requirement__Group_49__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_50(), "rule__Requirement__Group_50__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_51(), "rule__Requirement__Group_51__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_52(), "rule__Requirement__Group_52__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_53(), "rule__Requirement__Group_53__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_54(), "rule__Requirement__Group_54__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_55(), "rule__Requirement__Group_55__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_56(), "rule__Requirement__Group_56__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_57(), "rule__Requirement__Group_57__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_58(), "rule__Requirement__Group_58__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_59(), "rule__Requirement__Group_59__0");
			builder.put(grammarAccess.getRequirementAccess().getGroup_60(), "rule__Requirement__Group_60__0");
			builder.put(grammarAccess.getExprAccess().getGroup(), "rule__Expr__Group__0");
			builder.put(grammarAccess.getModelAccess().getReqAssignment(), "rule__Model__ReqAssignment");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_0_1(), "rule__Requirement__TrigAssignment_0_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_0_4(), "rule__Requirement__InvAssignment_0_4");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_1_1(), "rule__Requirement__TrigAssignment_1_1");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_1_8(), "rule__Requirement__ReaAssignment_1_8");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_2_1(), "rule__Requirement__TrigAssignment_2_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_2_4(), "rule__Requirement__InvAssignment_2_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_2_10(), "rule__Requirement__ReaAssignment_2_10");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_3_1(), "rule__Requirement__TrigAssignment_3_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_3_4(), "rule__Requirement__RelAssignment_3_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_3_9(), "rule__Requirement__ReaAssignment_3_9");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_4_1(), "rule__Requirement__TrigAssignment_4_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_4_4(), "rule__Requirement__RelAssignment_4_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_4_6(), "rule__Requirement__InvAssignment_4_6");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_4_16(), "rule__Requirement__ReaAssignment_4_16");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_5_1(), "rule__Requirement__TrigAssignment_5_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_5_8(), "rule__Requirement__InvAssignment_5_8");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_6_1(), "rule__Requirement__TrigAssignment_6_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_6_4(), "rule__Requirement__InvAssignment_6_4");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_6_8(), "rule__Requirement__RelAssignment_6_8");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_7_1(), "rule__Requirement__TrigAssignment_7_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_7_4(), "rule__Requirement__InvAssignment_7_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_7_8(), "rule__Requirement__ReaAssignment_7_8");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_7_12(), "rule__Requirement__Inv2Assignment_7_12");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_8_1(), "rule__Requirement__TrigAssignment_8_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_8_4(), "rule__Requirement__InvAssignment_8_4");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_8_12(), "rule__Requirement__RelAssignment_8_12");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_8_14(), "rule__Requirement__ReaAssignment_8_14");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_8_16(), "rule__Requirement__Inv2Assignment_8_16");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_9_1(), "rule__Requirement__TrigAssignment_9_1");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_9_4(), "rule__Requirement__NotdelAssignment_9_4");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_9_7(), "rule__Requirement__RelAssignment_9_7");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_9_9(), "rule__Requirement__ReaAssignment_9_9");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_10_1(), "rule__Requirement__TrigAssignment_10_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_10_5(), "rule__Requirement__FinAssignment_10_5");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_10_14(), "rule__Requirement__ReaAssignment_10_14");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_11_1(), "rule__Requirement__TrigAssignment_11_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_11_5(), "rule__Requirement__RelAssignment_11_5");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_11_7(), "rule__Requirement__FinAssignment_11_7");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_11_14(), "rule__Requirement__ReaAssignment_11_14");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_12_1(), "rule__Requirement__TrigAssignment_12_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_12_4(), "rule__Requirement__FinAssignment_12_4");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_12_16(), "rule__Requirement__NotdelAssignment_12_16");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_13_1(), "rule__Requirement__TrigAssignment_13_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_13_5(), "rule__Requirement__FinAssignment_13_5");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_13_16(), "rule__Requirement__NotdelAssignment_13_16");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_13_19(), "rule__Requirement__ReaAssignment_13_19");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_14_1(), "rule__Requirement__TrigAssignment_14_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_14_4(), "rule__Requirement__InvAssignment_14_4");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_14_6(), "rule__Requirement__NotdelAssignment_14_6");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_14_10(), "rule__Requirement__ReaAssignment_14_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_14_14(), "rule__Requirement__Inv2Assignment_14_14");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_15_1(), "rule__Requirement__TrigAssignment_15_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_15_4(), "rule__Requirement__InvAssignment_15_4");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_15_6(), "rule__Requirement__NotdelAssignment_15_6");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_15_10(), "rule__Requirement__RelAssignment_15_10");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_15_12(), "rule__Requirement__ReaAssignment_15_12");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_15_16(), "rule__Requirement__Inv2Assignment_15_16");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_16_1(), "rule__Requirement__TrigAssignment_16_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_16_4(), "rule__Requirement__InvAssignment_16_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_16_7(), "rule__Requirement__NotfinAssignment_16_7");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_16_11(), "rule__Requirement__RelAssignment_16_11");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_16_13(), "rule__Requirement__FinAssignment_16_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_16_17(), "rule__Requirement__Inv2Assignment_16_17");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_17_1(), "rule__Requirement__TrigAssignment_17_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_17_4(), "rule__Requirement__InvAssignment_17_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_17_7(), "rule__Requirement__NotfinAssignment_17_7");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_17_11(), "rule__Requirement__RelAssignment_17_11");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_17_13(), "rule__Requirement__FinAssignment_17_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_17_17(), "rule__Requirement__Inv2Assignment_17_17");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_17_20(), "rule__Requirement__ReaAssignment_17_20");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_18_1(), "rule__Requirement__TrigAssignment_18_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_18_4(), "rule__Requirement__InvAssignment_18_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_18_7(), "rule__Requirement__NotfinAssignment_18_7");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_18_10(), "rule__Requirement__FinAssignment_18_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_18_14(), "rule__Requirement__Inv2Assignment_18_14");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_19_1(), "rule__Requirement__TrigAssignment_19_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_19_4(), "rule__Requirement__InvAssignment_19_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_19_7(), "rule__Requirement__NotfinAssignment_19_7");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_19_11(), "rule__Requirement__FinAssignment_19_11");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_19_15(), "rule__Requirement__Inv2Assignment_19_15");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_19_18(), "rule__Requirement__ReaAssignment_19_18");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_20_1(), "rule__Requirement__TrigAssignment_20_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_20_4(), "rule__Requirement__InvAssignment_20_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_20_7(), "rule__Requirement__NotfinAssignment_20_7");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_20_11(), "rule__Requirement__FinAssignment_20_11");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_20_20(), "rule__Requirement__Inv2Assignment_20_20");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_20_22(), "rule__Requirement__NotdelAssignment_20_22");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_21_1(), "rule__Requirement__TrigAssignment_21_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_21_4(), "rule__Requirement__InvAssignment_21_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_21_7(), "rule__Requirement__NotfinAssignment_21_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_21_10(), "rule__Requirement__Fin2Assignment_21_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_21_15(), "rule__Requirement__Inv2Assignment_21_15");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_21_20(), "rule__Requirement__ReaAssignment_21_20");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_21_23(), "rule__Requirement__Inv3Assignment_21_23");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_22_1(), "rule__Requirement__TrigAssignment_22_1");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_22_4(), "rule__Requirement__InvAssignment_22_4");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_22_7(), "rule__Requirement__NotfinAssignment_22_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_22_10(), "rule__Requirement__Fin2Assignment_22_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_22_15(), "rule__Requirement__Inv2Assignment_22_15");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_22_20(), "rule__Requirement__NotdelAssignment_22_20");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_22_23(), "rule__Requirement__ReaAssignment_22_23");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_22_26(), "rule__Requirement__Inv3Assignment_22_26");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_23_1(), "rule__Requirement__TrigAssignment_23_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_23_4(), "rule__Requirement__RelAssignment_23_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_23_8(), "rule__Requirement__FinAssignment_23_8");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_23_17(), "rule__Requirement__NotdelAssignment_23_17");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_23_20(), "rule__Requirement__Rel2Assignment_23_20");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_24_1(), "rule__Requirement__TrigAssignment_24_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_24_4(), "rule__Requirement__RelAssignment_24_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_24_8(), "rule__Requirement__FinAssignment_24_8");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_24_17(), "rule__Requirement__NotdelAssignment_24_17");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_24_22(), "rule__Requirement__Rel2Assignment_24_22");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_24_24(), "rule__Requirement__ReaAssignment_24_24");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_25_1(), "rule__Requirement__TrigAssignment_25_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_25_4(), "rule__Requirement__RelAssignment_25_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_25_7(), "rule__Requirement__InvAssignment_25_7");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_25_10(), "rule__Requirement__NotfinAssignment_25_10");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_25_13(), "rule__Requirement__FinAssignment_25_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_25_18(), "rule__Requirement__Inv2Assignment_25_18");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_25_23(), "rule__Requirement__Rel2Assignment_25_23");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_26_1(), "rule__Requirement__TrigAssignment_26_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_26_4(), "rule__Requirement__RelAssignment_26_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_26_7(), "rule__Requirement__InvAssignment_26_7");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_26_10(), "rule__Requirement__NotfinAssignment_26_10");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_26_13(), "rule__Requirement__FinAssignment_26_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_26_19(), "rule__Requirement__Inv2Assignment_26_19");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_26_27(), "rule__Requirement__Rel2Assignment_26_27");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_26_29(), "rule__Requirement__ReaAssignment_26_29");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_26_31(), "rule__Requirement__Inv3Assignment_26_31");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_27_1(), "rule__Requirement__TrigAssignment_27_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_27_4(), "rule__Requirement__RelAssignment_27_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_27_7(), "rule__Requirement__InvAssignment_27_7");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_27_10(), "rule__Requirement__NotfinAssignment_27_10");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_27_13(), "rule__Requirement__FinAssignment_27_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_27_18(), "rule__Requirement__Inv2Assignment_27_18");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_27_23(), "rule__Requirement__NotdelAssignment_27_23");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_27_26(), "rule__Requirement__Rel2Assignment_27_26");
			builder.put(grammarAccess.getRequirementAccess().getTrigAssignment_28_1(), "rule__Requirement__TrigAssignment_28_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_28_4(), "rule__Requirement__RelAssignment_28_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_28_7(), "rule__Requirement__InvAssignment_28_7");
			builder.put(grammarAccess.getRequirementAccess().getNotfinAssignment_28_10(), "rule__Requirement__NotfinAssignment_28_10");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_28_14(), "rule__Requirement__FinAssignment_28_14");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_28_20(), "rule__Requirement__Inv2Assignment_28_20");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_28_25(), "rule__Requirement__NotdelAssignment_28_25");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_28_29(), "rule__Requirement__Rel2Assignment_28_29");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_28_31(), "rule__Requirement__ReaAssignment_28_31");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_28_33(), "rule__Requirement__Inv3Assignment_28_33");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_29_1(), "rule__Requirement__InvAssignment_29_1");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_30_4(), "rule__Requirement__ReaAssignment_30_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_31_1(), "rule__Requirement__InvAssignment_31_1");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_31_7(), "rule__Requirement__ReaAssignment_31_7");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_32_2(), "rule__Requirement__RelAssignment_32_2");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_32_7(), "rule__Requirement__ReaAssignment_32_7");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_33_2(), "rule__Requirement__RelAssignment_33_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_33_4(), "rule__Requirement__InvAssignment_33_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_33_14(), "rule__Requirement__ReaAssignment_33_14");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_34_1(), "rule__Requirement__InvAssignment_34_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_34_6(), "rule__Requirement__RelAssignment_34_6");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_35_1(), "rule__Requirement__NotdelAssignment_35_1");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_35_5(), "rule__Requirement__RelAssignment_35_5");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_35_7(), "rule__Requirement__ReaAssignment_35_7");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_36_1(), "rule__Requirement__InvAssignment_36_1");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_36_5(), "rule__Requirement__ReaAssignment_36_5");
			builder.put(grammarAccess.getRequirementAccess().getE1Assignment_37_1(), "rule__Requirement__E1Assignment_37_1");
			builder.put(grammarAccess.getRequirementAccess().getE2Assignment_37_8(), "rule__Requirement__E2Assignment_37_8");
			builder.put(grammarAccess.getRequirementAccess().getE3Assignment_37_10(), "rule__Requirement__E3Assignment_37_10");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_38_5(), "rule__Requirement__FinAssignment_38_5");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_38_15(), "rule__Requirement__ReaAssignment_38_15");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_39_5(), "rule__Requirement__FinAssignment_39_5");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_39_16(), "rule__Requirement__ReaAssignment_39_16");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_39_19(), "rule__Requirement__RelAssignment_39_19");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_40_5(), "rule__Requirement__FinAssignment_40_5");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_40_14(), "rule__Requirement__NotdelAssignment_40_14");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_41_5(), "rule__Requirement__FinAssignment_41_5");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_41_16(), "rule__Requirement__NotdelAssignment_41_16");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_41_19(), "rule__Requirement__ReaAssignment_41_19");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_42_1(), "rule__Requirement__InvAssignment_42_1");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_42_3(), "rule__Requirement__NotdelAssignment_42_3");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_42_6(), "rule__Requirement__ReaAssignment_42_6");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_43_2(), "rule__Requirement__InvAssignment_43_2");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_43_5(), "rule__Requirement__FinAssignment_43_5");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_43_8(), "rule__Requirement__RelAssignment_43_8");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_43_13(), "rule__Requirement__Fin2Assignment_43_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_43_15(), "rule__Requirement__Inv2Assignment_43_15");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_44_1(), "rule__Requirement__InvAssignment_44_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_44_4(), "rule__Requirement__FinAssignment_44_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_44_8(), "rule__Requirement__ReaAssignment_44_8");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_45_2(), "rule__Requirement__InvAssignment_45_2");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_45_5(), "rule__Requirement__FinAssignment_45_5");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_45_8(), "rule__Requirement__RelAssignment_45_8");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_45_13(), "rule__Requirement__Fin2Assignment_45_13");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_45_15(), "rule__Requirement__Inv2Assignment_45_15");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_45_18(), "rule__Requirement__ReaAssignment_45_18");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_46_2(), "rule__Requirement__InvAssignment_46_2");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_46_5(), "rule__Requirement__FinAssignment_46_5");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_46_8(), "rule__Requirement__Fin2Assignment_46_8");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_46_18(), "rule__Requirement__Inv2Assignment_46_18");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_46_20(), "rule__Requirement__NotdelAssignment_46_20");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_47_1(), "rule__Requirement__InvAssignment_47_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_47_4(), "rule__Requirement__FinAssignment_47_4");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_47_8(), "rule__Requirement__ReaAssignment_47_8");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_48_1(), "rule__Requirement__InvAssignment_48_1");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_48_4(), "rule__Requirement__FinAssignment_48_4");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_48_12(), "rule__Requirement__NotdelAssignment_48_12");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_48_15(), "rule__Requirement__ReaAssignment_48_15");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_49_4(), "rule__Requirement__RelAssignment_49_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_49_6(), "rule__Requirement__FinAssignment_49_6");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_49_18(), "rule__Requirement__NotdelAssignment_49_18");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_49_21(), "rule__Requirement__Rel2Assignment_49_21");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_50_4(), "rule__Requirement__RelAssignment_50_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_50_6(), "rule__Requirement__FinAssignment_50_6");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_50_18(), "rule__Requirement__NotdelAssignment_50_18");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_50_21(), "rule__Requirement__Rel2Assignment_50_21");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_50_23(), "rule__Requirement__ReaAssignment_50_23");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_51_2(), "rule__Requirement__RelAssignment_51_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_51_5(), "rule__Requirement__InvAssignment_51_5");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_51_8(), "rule__Requirement__FinAssignment_51_8");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_51_12(), "rule__Requirement__Fin2Assignment_51_12");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_51_20(), "rule__Requirement__Inv2Assignment_51_20");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_51_26(), "rule__Requirement__Rel2Assignment_51_26");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_52_4(), "rule__Requirement__RelAssignment_52_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_52_7(), "rule__Requirement__InvAssignment_52_7");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_52_10(), "rule__Requirement__FinAssignment_52_10");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_52_14(), "rule__Requirement__Fin2Assignment_52_14");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_52_22(), "rule__Requirement__Inv2Assignment_52_22");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_52_30(), "rule__Requirement__Rel2Assignment_52_30");
			builder.put(grammarAccess.getRequirementAccess().getRea2Assignment_52_32(), "rule__Requirement__Rea2Assignment_52_32");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_52_34(), "rule__Requirement__Inv3Assignment_52_34");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_53_4(), "rule__Requirement__RelAssignment_53_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_53_8(), "rule__Requirement__InvAssignment_53_8");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_53_11(), "rule__Requirement__FinAssignment_53_11");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_53_15(), "rule__Requirement__Fin2Assignment_53_15");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_53_23(), "rule__Requirement__Inv2Assignment_53_23");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_53_25(), "rule__Requirement__NotdelAssignment_53_25");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_53_31(), "rule__Requirement__Rel2Assignment_53_31");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_54_4(), "rule__Requirement__RelAssignment_54_4");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_54_8(), "rule__Requirement__InvAssignment_54_8");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_54_11(), "rule__Requirement__FinAssignment_54_11");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_54_15(), "rule__Requirement__Fin2Assignment_54_15");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_54_23(), "rule__Requirement__Inv2Assignment_54_23");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_54_25(), "rule__Requirement__NotdelAssignment_54_25");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_54_31(), "rule__Requirement__Rel2Assignment_54_31");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_54_33(), "rule__Requirement__ReaAssignment_54_33");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_54_35(), "rule__Requirement__Inv3Assignment_54_35");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_55_2(), "rule__Requirement__RelAssignment_55_2");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_55_5(), "rule__Requirement__FinAssignment_55_5");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_55_16(), "rule__Requirement__NotdelAssignment_55_16");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_55_19(), "rule__Requirement__Rel2Assignment_55_19");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_56_4(), "rule__Requirement__RelAssignment_56_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_56_7(), "rule__Requirement__FinAssignment_56_7");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_56_16(), "rule__Requirement__NotdelAssignment_56_16");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_56_19(), "rule__Requirement__Rel2Assignment_56_19");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_56_21(), "rule__Requirement__ReaAssignment_56_21");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_57_2(), "rule__Requirement__RelAssignment_57_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_57_4(), "rule__Requirement__InvAssignment_57_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_57_7(), "rule__Requirement__FinAssignment_57_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_57_10(), "rule__Requirement__Fin2Assignment_57_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_57_16(), "rule__Requirement__Inv2Assignment_57_16");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_57_21(), "rule__Requirement__Rel2Assignment_57_21");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_58_2(), "rule__Requirement__RelAssignment_58_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_58_4(), "rule__Requirement__InvAssignment_58_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_58_7(), "rule__Requirement__FinAssignment_58_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_58_10(), "rule__Requirement__Fin2Assignment_58_10");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_58_16(), "rule__Requirement__Inv2Assignment_58_16");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_58_21(), "rule__Requirement__Rel2Assignment_58_21");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_58_23(), "rule__Requirement__ReaAssignment_58_23");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_58_25(), "rule__Requirement__Inv3Assignment_58_25");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_59_2(), "rule__Requirement__RelAssignment_59_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_59_4(), "rule__Requirement__InvAssignment_59_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_59_7(), "rule__Requirement__FinAssignment_59_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_59_9(), "rule__Requirement__Fin2Assignment_59_9");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_59_16(), "rule__Requirement__Inv2Assignment_59_16");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_59_18(), "rule__Requirement__NotdelAssignment_59_18");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_59_23(), "rule__Requirement__Rel2Assignment_59_23");
			builder.put(grammarAccess.getRequirementAccess().getRelAssignment_60_2(), "rule__Requirement__RelAssignment_60_2");
			builder.put(grammarAccess.getRequirementAccess().getInvAssignment_60_4(), "rule__Requirement__InvAssignment_60_4");
			builder.put(grammarAccess.getRequirementAccess().getFinAssignment_60_7(), "rule__Requirement__FinAssignment_60_7");
			builder.put(grammarAccess.getRequirementAccess().getFin2Assignment_60_11(), "rule__Requirement__Fin2Assignment_60_11");
			builder.put(grammarAccess.getRequirementAccess().getInv2Assignment_60_17(), "rule__Requirement__Inv2Assignment_60_17");
			builder.put(grammarAccess.getRequirementAccess().getNotdelAssignment_60_19(), "rule__Requirement__NotdelAssignment_60_19");
			builder.put(grammarAccess.getRequirementAccess().getRel2Assignment_60_25(), "rule__Requirement__Rel2Assignment_60_25");
			builder.put(grammarAccess.getRequirementAccess().getReaAssignment_60_27(), "rule__Requirement__ReaAssignment_60_27");
			builder.put(grammarAccess.getRequirementAccess().getInv3Assignment_60_29(), "rule__Requirement__Inv3Assignment_60_29");
			builder.put(grammarAccess.getExprAccess().getObjAssignment_0(), "rule__Expr__ObjAssignment_0");
			builder.put(grammarAccess.getExprAccess().getPropAssignment_2(), "rule__Expr__PropAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TemporGrammarAccess grammarAccess;

	@Override
	protected InternalTemporParser createParser() {
		InternalTemporParser result = new InternalTemporParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TemporGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TemporGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
