/*
 * generated by Xtext 2.26.0
 */
package iae;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TemporStandaloneSetup extends TemporStandaloneSetupGenerated {

	public static void doSetup() {
		new TemporStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
